apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deployment
  namespace: factory
  labels:
    app: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
        - name: data-service
          imagePullPolicy: Always
          image: juliantheking/data-service
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-credentials
                  key: POSTRGES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD