server:
  port: 9099
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
data:
  sources:
    temperatureMean: temperature
    pressureMean: pressure
    flowRateMean: flowRate
    gasCompositionMean: gasComposition
    compressorState: compressorState
