server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://database-svc:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
data:
  dataSources:
    temperatureMean:
      sensorType: temperatureMean
      availableLabels: [ BeforeBoiler, AfterBoiler, Return, Begin ]
    pressureMean:
      sensorType: pressureMean
      availableLabels: [ AfterReturnCompressor, BeforeReturnCompressor, AfterBeginCompressor, BeforeBeginCompressor ]
    flowRateMean:
      sensorType: flowRateMean
      availableLabels: [ CompressedReturn, NotCompressedReturn, Input, Output ]
    gasCompositionMean:
      sensorType: gasCompositionMean
      availableLabels: [ Begin, Input, Output, Return ]
    compressorState:
      sensorType: compressorState
      availableLabels: [ ReturnCompressor, BeginCompressor ]
